name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # synchronized with `.readthedocs.yml`
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PDM
      run: curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3
    - name: Install dependencies
      run: |
        pdm sync -G docs
    - name: Run sphinx-build
      run: |
        pdm run sphinx-build -n docs build/sphinx
